@base_url = http://localhost:5056
@email = genjiru37@gmail.com
POST {{base_url}}/api/register
Content-Type: application/json

{
    "Email" : "genjirudd20dsdsdsdsdds0@gmail.com",
    "Password": "Elfocrash@0077",
    "ConfirmPassword": "Elfocrash@0077"
}

###
